### ISSUE TITLE
No license = all rights reserved, but I want to copy+modify+distribute a patched version

### ISSUE THREAD

**Issue by mbideau** [bucko909/btrfs-send-go#1]
Hi,
First thank you very much for publishing that piece of code.
I have made some patches localy to improve it and I want to publish them (I might also make a PR to your project).
But I can't do anything until you formally grant me the right to copy+modify+distribute, or choose yourself a license that allow me to do that (like GPL, BSD, MIT, Apache, etc).
If you could do so, I will be glad to share my tiny improvments :)
Have a good year.
PS: sorry to dig up a project that was made several years ago, but it is still relevant today (for me)

**Comment by bucko909** [comment]
Wow, I didn't expect this! FYI this was originally my attempt to get Docker to have a more efficient implementation of the `btrfs` backend, but I never got around to finishing it mostly because I have no idea how to read or write golang. :)

**Comment by bucko909** [comment]
Hopefully the new LICENSE file closes this. Enjoy.

**Comment by mbideau** [comment]
Great thank you very much :+1:
