### ISSUE TITLE
Your code has grow big :wink: 

### ISSUE THREAD

**Issue by mbideau** [bucko909/btrfs-send-go#2]
Hey @bucko909, I am opening that issue, just to let you know that I have made a lot of bug fixes and improvements to your original version, including a full CI toolchain.
I also sub-licenced it to _GPLv3_ to ensure people forking that new version would share their code. Hope you don't mind ?
Check it out [here](https://github.com/mbideau/btrfs-diff-go) if you want.
Tell me what you think about it ...

Thank you again for the bootstraping :pray: :wink: 
Have a nice day.

**Comment by bucko909** [comment]
You are quite entitled to change the license, though I'm personally not a fan of restricting others' use of code (hence why I generally choose MIT). The main concern I'd have is if it could be embedded into Docker with that license (which was my original use-case -- fixing the awful speed of diffing on the btrfs Docker driver). Docker's Apache, so I don't think it can be. Up to you, though!

I might drop an README upgrade pointing to your fork as it's clearly in a more mature and useful state than my code!

**Comment by mbideau** [comment]
Hey thank you very much for your feedback and support ! :pray:

About the license, I am totally OK to change back to _MIT_ if a big project like _Docker_ is prevented to use it, and it could benefit many people... Let me know if that's an issue.

**Comment by bucko909** [comment]
I think Docker will let you know if it's an issue. I doubt it matters much, and my code remains MIT anyway. I just felt that I'd give my reasoning for license choice in response to you giving yours!
